routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/set-locale/{locale?}', function ($locale) {
    session(['locale' => $locale]);
    app()->setLocale($locale);
    return redirect()->back();
});
Route::get('/logout', function () {
    \Auth::logout();
    return redirect('/');
});
Route::get('/info-tours/{id?}', [App\Http\Controllers\ToursController::class, 'info_tours']);
Route::group(['middleware' => ['setlocale']], function() {

    Route::get('/', function () {

        return view('layouts.index');
    });

    Auth::routes();

    Route::get('/check', [App\Http\Controllers\Auth\RegisterController::class, 'check']);
    Route::post('/login/role', [App\Http\Controllers\Auth\LoginController::class,  'login_check_role']);

    Route::resource('tour', 'TourController');
    Route::post('/tour/update/{id?}', [App\Http\Controllers\TourController::class, 'updates']);
    Route::any('/all-tour', [App\Http\Controllers\TourController::class, 'all_tours']);
    Route::get('/about_us', function () {
        return view('layouts.about');
    });

    Route::get('/create-article', [App\Http\Controllers\ArticleController::class, 'create_articles']);
    Route::post('/save-articles', [App\Http\Controllers\ArticleController::class, 'save_articles']);
    Route::get('/blogs/{category_id?}', [App\Http\Controllers\ArticleController::class, 'all_articles']);
    Route::any('/reset-password/{token?}', [App\Http\Controllers\CustomRegController::class,  'reset_password']);
    Route::post('/pass', [App\Http\Controllers\CustomRegController::class,  'pass']);
    Route::get('/info', function ($email = null) {
        $email = session()->get('email');
        \Auth::logout();
        return view('layouts.info', ['email' => $email ]);
    });
    Route::get('/news', [App\Http\Controllers\ArticleController::class, 'all_news']);
    Route::get('/create-news', [App\Http\Controllers\ArticleController::class, 'create_news']);
    Route::post('/save-news', [App\Http\Controllers\ArticleController::class, 'save_news']);

    Route::group(['middleware' => ['auth']], function(){
        Route::get('/conversations', 'ChatController@index')->name('conversations');

        Route::get('/last-orders', function () {
            return view('layouts.orders.order');
        });
        Route::resource('tours', App\Http\Controllers\ToursController::class);
        Route::get('/cabinet', [App\Http\Controllers\CabinetController::class,  'index']);
        Route::post('/update_user', [App\Http\Controllers\CabinetController::class,  'update_user']);
        Route::post('/generate_code', [App\Http\Controllers\CabinetController::class,  'generate_code']);
        Route::post('/check_code', [App\Http\Controllers\CabinetController::class,  'check_code']);
        Route::post('/contacts', [App\Http\Controllers\CabinetController::class,  'contacts']);
        Route::post('/description_profile', [App\Http\Controllers\CabinetController::class,  'description_profile']);
        Route::post('/notifications', [App\Http\Controllers\CabinetController::class,  'notifications']);
        Route::post('/reset_password', [App\Http\Controllers\CabinetController::class,  'reset_password']);
    });



// Route::get('/', function () {
//     return view('home.index');
// });


    Auth::routes();
    Route::get('activate', 'AuthController@verifyAccount');

    Route::get('/home', 'HomeController@index');

    // Route::group(['middleware' => ['user.activated', 'auth']], function () {
    //view routes
    // Route::get('/conversations', 'ChatController@index')->name('conversations');
    Route::get('profile', 'UserController@getProfile');
    Route::group(['namespace' => 'API'], function () {

        //get all user list for chat
        Route::get('users-list', 'UserAPIController@getUsersList');
        Route::get('get-users', 'UserAPIController@getUsers');
        Route::delete('remove-profile-image', 'UserAPIController@removeProfileImage');
        /** Change password */
        Route::post('change-password', 'UserAPIController@changePassword');
        Route::get('conversations/{ownerId}/archive-chat', 'UserAPIController@archiveChat');

        Route::get('get-profile', 'UserAPIController@getProfile');
        Route::post('profile', 'UserAPIController@updateProfile')->name('update.profile');
        Route::post('update-last-seen', 'UserAPIController@updateLastSeen');

        Route::post('send-message',
            'ChatAPIController@sendMessage')->name('conversations.store')->middleware('sendMessage');
        Route::get('users/{id}/conversation', 'UserAPIController@getConversation');
        Route::get('conversations-list', 'ChatAPIController@getLatestConversations');
        Route::get('archive-conversations', 'ChatAPIController@getArchiveConversations');
        Route::post('read-message', 'ChatAPIController@updateConversationStatus');
        Route::post('file-upload', 'ChatAPIController@addAttachment')->name('file-upload');
        Route::post('image-upload', 'ChatAPIController@imageUpload')->name('image-upload');
        Route::get('conversations/{userId}/delete', 'ChatAPIController@deleteConversation');
        Route::post('conversations/message/{conversation}/delete', 'ChatAPIController@deleteMessage');
        Route::post('conversations/{conversation}/delete', 'ChatAPIController@deleteMessageForEveryone');
        Route::get('/conversations/{conversation}', 'ChatAPIController@show');
        Route::post('send-chat-request', 'ChatAPIController@sendChatRequest')->name('send-chat-request');
        Route::post('accept-chat-request', 'ChatAPIController@acceptChatRequest')->name('accept-chat-request');
        Route::post('decline-chat-request', 'ChatAPIController@declineChatRequest')->name('decline-chat-request');

        /** Web Notifications */
        Route::put('update-web-notifications', 'UserAPIController@updateNotification');

        /** BLock-Unblock User */
        Route::put('users/{user}/block-unblock', 'BlockUserAPIController@blockUnblockUser');
        Route::get('blocked-users', 'BlockUserAPIController@blockedUsers');

        /** My Contacts */
        Route::get('my-contacts', 'UserAPIController@myContacts')->name('my-contacts');

        /** Groups API */
        Route::post('groups', 'GroupAPIController@create');
        Route::post('groups/{group}', 'GroupAPIController@update');
        Route::get('groups', 'GroupAPIController@index');
        Route::get('groups/{group}', 'GroupAPIController@show');
        Route::put('groups/{group}/add-members', 'GroupAPIController@addMembers');
        Route::delete('groups/{group}/members/{user}', 'GroupAPIController@removeMemberFromGroup');
        Route::delete('groups/{group}/leave', 'GroupAPIController@leaveGroup');
        Route::delete('groups/{group}/remove', 'GroupAPIController@removeGroup');
        Route::put('groups/{group}/members/{user}/make-admin', 'GroupAPIController@makeAdmin');
        Route::put('groups/{group}/members/{user}/dismiss-as-admin', 'GroupAPIController@dismissAsAdmin');
        Route::get('users-blocked-by-me', 'BlockUserAPIController@blockUsersByMe');

        Route::get('notification/{notification}/read', 'NotificationController@readNotification');
        Route::get('notification/read-all', 'NotificationController@readAllNotification');

        //set user custom status route
        Route::post('set-user-status', 'UserAPIController@setUserCustomStatus')->name('set-user-status');
        Route::get('clear-user-status', 'UserAPIController@clearUserCustomStatus')->name('clear-user-status');

        //report user
        Route::post('report-user', 'ReportUserController@store')->name('report-user.store');
    });
});

Route::group(['middleware' => ['role:Admin', 'auth', 'user.activated']], function () {
    Route::resource('users', 'UserController');
    Route::post('users/{user}/active-de-active', 'UserController@activeDeActiveUser')
        ->name('active-de-active-user');
    Route::post('users/{user}/update', 'UserController@update');
    Route::delete('users/{user}/archive', 'UserController@archiveUser');
    Route::post('users/restore', 'UserController@restoreUser');

    Route::resource('roles', 'RoleController');
    Route::post('roles/{role}/update', 'RoleController@update');

    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::post('settings', 'SettingsController@update')->name('settings.update');

    Route::resource('reported-users', 'ReportUserController');
});

Route::group(['middleware' => ['web']], function () {

    Route::get('login/{provider}', 'Auth\SocialAuthController@redirect');
    Route::get('login/{provider}/callback', 'Auth\SocialAuthController@callback');
// });
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use App\Queries\UserDataTable;
use App\Repositories\UserRepository;
use DataTables;
use Exception;
use Hash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Response;

class UserController extends AppBaseController
{
    /** @var  UserRepository */
    private $userRepository;

    public function __construct(UserRepository $userRepo)
    {
        $this->userRepository = $userRepo;
    }

    /**
     * @return Factory|View
     */
    public function getProfile()
    {
        return view('profile');
    }

    /**
     * Display a listing of the User.
     *
     * @param  Request  $request
     * @throws Exception
     * @return Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of((new UserDataTable())->get($request->only(['filter_user'])))->make(true);
        }
        $roles = Role::all()->pluck('name', 'id')->toArray();

        return view('users.index')->with([
            'roles' => $roles,
        ]);
    }

    /**
     * Show the form for creating a new User.
     *
     * @return Response
     */
    public function create()
    {
        $roles = Role::all()->pluck('name', 'id')->toArray();

        return view('users.create')->with(['roles' => $roles]);
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  CreateUserRequest  $request
     *
     * @return Response
     */
    public function store(CreateUserRequest $request)
    {
        $input = $this->validateInput($request->all());

        $this->userRepository->store($input);

        return $this->sendSuccess('User saved successfully.');
    }

    /**
     * Display the specified User.
     * @param  User  $user
     *
     * @return Response
     */
    public function show(User $user)
    {
        $user->roles;
        $user = $user->apiObj();

        return view('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified User.
     *
     * @param  User  $user
     * @return Response
     */
    public function edit(User $user)
    {
        $user->roles;
        $user = $user->apiObj();

        return $this->sendResponse(['user' => $user], 'User retrieved successfully.');
    }

    /**
     * Update the specified User in storage.
     *
     * @param  User  $user
     * @param  UpdateUserRequest  $request
     *
     * @return Response
     */
    public function update(User $user, UpdateUserRequest $request)
    {
        if ($user->is_system) {
            return $this->sendError('You can not update system generated user.');
        }

        $input = $this->validateInput($request->all());
        $this->userRepository->update($input, $user->id);

        return $this->sendSuccess('User updated successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param User $user
     * 
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function archiveUser(User $user)
    {
        if ($user->is_system) {
            return $this->sendError('You can not archive system generated user.');
        }
        $this->userRepository->delete($user->id);

        return $this->sendSuccess('User archived successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param Request $request
     * 
     * @return JsonResponse
     */
    public function restoreUser(Request $request)
    {
        $id = $request->get('id');
        $this->userRepository->restore($id);

        return $this->sendSuccess('User restored successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param integer $id
     * 
     * @throws Exception
     * 
     * @return JsonResponse
     */
    public function destroy($id)
    {
        $user = User::withTrashed()->whereId($id)->first();
        if ($user->is_system) {
            return $this->sendError('You can not delete system generated user.');
        }
        $this->userRepository->deleteUser($user->id);

        return $this->sendSuccess('User deleted successfully.');
    }

    /**
     * @param  User  $user
     *
     * @return JsonResponse
     */
    public function activeDeActiveUser(User $user)
    {
        $this->userRepository->checkUserItSelf($user->id);
        $this->userRepository->activeDeActiveUser($user->id);

        return $this->sendSuccess('User updated successfully.');
    }

    public function validateInput($input)
    {
        if (isset($input['password']) && ! empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            unset($input['password']);
        }

        $input['is_active'] = (! empty($input['is_active'])) ? 1 : 0;

        return $input;
    }
}

resources/views/users/create.blade.php
<div id="create_user_modal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{ __('messages.new_user') }}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="form-group col-sm-12">
                <div class="" id="validationErrorsBox"></div>
            </div>
            {!! Form::open(['id'=>'createUserForm', 'method' => 'POST']) !!}
            <div class="modal-body">
                @include('users.fields')
            </div>
            {!! Form::close() !!}
        </div>

    </div>
</div>

resources/views/users/edit.blade.php
<div id="edit_user_modal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{ __('messages.edit_user') }}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            {!! Form::open(['id'=>'editUserForm', 'method' => 'POST', 'files' => true]) !!}
            {!! Form::hidden('id','',['id' => 'edit_user_id']) !!}
            <div class="modal-body">
                <div class="row col-sm-12">
                    <div class="col-sm-12">
                        <div class="alert alert-danger" style="display: none" id="editValidationErrorsBox"></div>
                    </div>
                    <div class="col-sm-6">
                        <div class="row">
                            <!-- Name Field -->
                            <div class="form-group col-sm-6">
                                {!! Form::label('name', __('messages.full_name') ) !!}<span class="red">*</span>
                                {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'edit_name', 'required']) !!}
                            </div>

                            <!-- Phone Field -->
                            <div class="form-group col-sm-6">
                                {!! Form::label('phone', __('messages.phone') ) !!}
                                {!! Form::text('phone', null, ['class' => 'form-control', 'id' => 'edit_phone']) !!}
                            </div>
                        </div>

                        <!-- Email Field -->
                        <div class="form-group">
                            {!! Form::label('email', __('messages.email') ) !!}<span class="red">*</span>
                            {!! Form::email('email', null, ['class' => 'form-control', 'id' => 'edit_email',  'required']) !!}
                        </div>

                        <div class="row">
                            <div class="form-group  col-sm-6">
                                <label>{{ __('messages.gender') }}</label>
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="edit_male" name="gender"
                                            value="{{ \App\Models\User::MALE }}"> <label class="custom-control-label"
                                            for="edit_male">
                                        {{ __('messages.male') }}
                                    </label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="edit_female" name="gender"
                                           value="{{ \App\Models\User::FEMALE }}"> <label class="custom-control-label"
                                                                                          for="edit_female">
                                        {{ __('messages.female') }}
                                    </label>
                                </div>
                            </div>

                            <div class="form-group col-sm-6">
                                <label>{{ __('messages.group.privacy') }}</label>
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="editPrivacyPrivate"
                                           name="privacy" value="0"> <label class="custom-control-label"
                                                                            for="editPrivacyPrivate">
                                        {{ __('messages.group.private') }}
                                        <i class="fa fa-question-circle ml-2 question-type-open cursor-pointer"
                                           data-toggle="tooltip" data-placement="top" title=""
                                           data-original-title="All group members can send messages into the group."></i>
                                    </label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="editPrivacyPublic"
                                           name="privacy" value="1"> <label class="custom-control-label"
                                                                            for="editPrivacyPublic">
                                        {{ __('messages.group.public') }}
                                        <i class="fa fa-question-circle ml-2 question-type-open cursor-pointer"
                                           data-toggle="tooltip" data-placement="top" title=""
                                           data-original-title="All group members can send messages into the group."></i>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <!-- Bio Field -->
                        <div class="form-group">
                            {!! Form::label('bio', __('messages.bio') ) !!}
                            {!! Form::textarea('about', null, ['class' => 'form-control user__bio', 'rows' => 3, 'id' => 'edit_about']) !!}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="profile__inner m-auto">
                                <div class="text-center profile__img-wrapper">
                                    <img src="{{ isset($user->photo_url) ? $user->photo_url : getDefaultAvatar() }}"
                                         alt="" id="edit_upload-photo-img">
                                </div>
                                <div class="text-center mt-2 user__upload-btn">
                                    <label class="btn profile__update-label">
                                        {{ __('messages.upload_photo') }}
                                        <input id="edit_upload-photo" class="d-none" name="photo" type="file">
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <!-- Is Active Field -->
                            <div class="form-group col-sm-6">
                                {!! Form::label('is_active', __('messages.is_active') ) !!}<span class="red">*</span>
                                {!! Form::select('is_active', [1 => 'Active', 0 => 'In Active'], (isset($user->is_active)) ? $user->is_active : [],  ['class' => 'form-control', 'id' => 'edit_is_active',  'required']) !!}
                            </div>

                            <!-- Role Field -->
                            <div class="form-group col-sm-6">
                                {!! Form::label('role', __('messages.role') ) !!}<span class="red">*</span>
                                {!! Form::select('role_id', $roles, (isset($user->role_id)) ? $user->role_id : [],  ['class' => 'form-control','placeholder' => 'Select Role', 'id' => 'edit_role_id']) !!}
                            </div>
                        </div>

                    </div>

                    <!-- Submit Field -->
                    <div class="text-right form-group col-sm-12">
                        {!! Form::submit(__('messages.save'), ['class' => 'btn btn-primary', 'id' => 'editBtnSave']) !!}
                        <button type="button" class="btn btn-secondary ml-1"
                                data-dismiss="modal">{{ __('messages.cancel') }}</button>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
        </div>

    </div>
</div>

resources/views/users/fields.blade.php
<div class="row col-sm-12">
    <div class="col-sm-12">
        <div class="alert alert-danger" style="display: none" id="validationErrorsBox"></div>
    </div>
    <div class="col-sm-6">
        <div class="row">
            <!-- Name Field -->
            <div class="form-group col-sm-6">
                {!! Form::label('name', __('messages.full_name') ) !!}<span class="red">*</span>
                {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'required']) !!}
            </div>

            <!-- Phone Field -->
            <div class="form-group col-sm-6">
                {!! Form::label('phone', __('messages.phone') ) !!}
                {!! Form::text('phone', null, ['class' => 'form-control', 'id' => 'phone']) !!}
            </div>
        </div>

        <!-- Email Field -->
        <div class="form-group">
            {!! Form::label('email', __('messages.email') ) !!}<span class="red">*</span>
            {!! Form::email('email', null, ['class' => 'form-control', 'id' => 'email', 'required']) !!}
        </div>

        <div class="row">
            <div class="form-group col-sm-6">
                <label>{{ __('messages.gender') }}</label>
                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" id="male" name="gender"
                            value="{{ \App\Models\User::MALE }}"> <label class="custom-control-label" for="male">
                        {{ __('messages.male') }}
                    </label>
                </div>
                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" id="female" name="gender"
                           value="{{ \App\Models\User::FEMALE }}"> <label class="custom-control-label" for="female">
                        {{ __('messages.female') }}
                    </label>
                </div>
            </div>
            <div class="form-group col-sm-6">
                <label>{{ __('messages.group.privacy') }}</label>
                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" id="privacyPrivate" name="privacy" value="0">
                    <label class="custom-control-label" for="privacyPrivate">
                        {{ __('messages.group.private') }}
                        <i class="fa fa-question-circle ml-2 question-type-open cursor-pointer" data-toggle="tooltip"
                           data-placement="top" title=""
                           data-original-title="All group members can send messages into the group."></i> </label>
                </div>
                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" id="privacyPublic" name="privacy" value="1"> <label
                            class="custom-control-label" for="privacyPublic">
                        {{ __('messages.group.public') }}
                        <i class="fa fa-question-circle ml-2 question-type-open cursor-pointer" data-toggle="tooltip"
                           data-placement="top" title=""
                           data-original-title="All group members can send messages into the group."></i> </label>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Is Active Field -->
            <div class="form-group col-sm-6">
                {!! Form::label('is_active', __('messages.is_active') ) !!}<span class="red">*</span>
                {!! Form::select('is_active', [1 => 'Active', 0 => 'In Active'], (isset($user->is_active)) ? $user->is_active : [],  ['class' => 'form-control', 'id' => 'is_active',  'required']) !!}
            </div>

            <!-- Role Field -->
            <div class="form-group col-sm-6">
                {!! Form::label('role', __('messages.role') ) !!}<span class="red">*</span>
                {!! Form::select('role_id', $roles, (isset($user->role_id)) ? $user->role_id : [],  ['class' => 'form-control','placeholder' => 'Select Role', 'id' => 'role_id', 'required']) !!}
            </div>
        </div>

        <div class="row">
            <div class="form-group col-sm-6">
                {!! Form::label('password', __('messages.password') ) !!}<span class="red">*</span>
                <input type="password" name="password" class="form-control" onkeypress="return avoidSpace(event)"
                       required>
            </div>
            <div class="form-group col-sm-6">
                {!! Form::label('password', __('messages.confirm_password') ) !!}<span class="red">*</span>
                <input type="password" name="password_confirmation" class="form-control"
                       onkeypress="return avoidSpace(event)" required>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group">
            <div class="profile__inner m-auto">
                <div class="text-center profile__img-wrapper">
                    <img src="{{ isset($user->photo_url) ? $user->photo_url : getDefaultAvatar() }}" alt=""
                         id="upload-photo-img">
                </div>
                <div class="text-center mt-2 user__upload-btn">
                    <label class="btn profile__update-label">
                        {{ __('messages.upload_photo') }}
                        <input id="upload-photo" class="d-none" name="photo" type="file">
                    </label>
                </div>
            </div>
        </div>

        <!-- Bio Field -->
        <div class="form-group">
            {!! Form::label('bio', __('messages.bio') ) !!}
            {!! Form::textarea('about', null, ['class' => 'form-control user__bio', 'rows' => 3, 'id' => 'about']) !!}
        </div>
    </div>

    <!-- Submit Field -->
    <div class="text-right form-group col-sm-12">
        {!! Form::submit(__('messages.save'), ['class' => 'btn btn-primary', 'id' => 'createBtnSave']) !!}
        <button type="button" class="btn btn-secondary ml-1" data-dismiss="modal">{{ __('messages.cancel') }}</button>
    </div>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.users') }}
@endsection
@section('page_css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/dataTable.min.css') }}"/>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header page-header">
                             <div class="pull-left page__heading">
                                 {{ __('messages.users') }}
                             </div>
                             <div class="filter-container">
                                 <div class="mr-2">
                                     {!!Form::select('drp_users', \App\Models\User::FILTER_ARRAY, \App\Models\User::FILTER_ALL, ['id' => 'filter_user','class'=>'form-control','style'=>'min-width:150px;'])  !!}
                                 </div>
                                 <button type="button" class="pull-right btn btn-primary filter-container__btn" data-toggle="modal" data-target="#create_user_modal">{{ __('messages.new_user') }}</button>
                             </div>
                         </div>
                         <div class="card-body">
                             @include('users.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
    @include('users.create')
    @include('users.edit')
    @include('users.templates.action_icons')
@endsection
@section('page_js')
    <script type="text/javascript" src="{{ asset('js/dataTable.min.js') }}"></script>
@endsection
@section('scripts')
    <script>
        let createUserUrl = "{{ route('users.store') }}";
        let usersUrl = "{{ url('users') }}/";
        let defaultImageAvatar = "{{ getDefaultAvatar() }}/";
    </script>
    <script src="{{ mix('assets/js/admin/users/user.js') }}"></script>
    <script src="{{ mix('assets/js/admin/users/edit_user.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/custom-datatables.js') }}"></script>
@endsection